#!/bin/bash
git clone github:bitly/data_hacks.git ~/src/data_hacks
git clone github:burocratik/outdated-browser.git ~/src/outdated-browser
git clone github:cloudnull/turbolift.git ~/src/turbolift
git clone github:dm0-/window_merge.git ~/src/window_merge
git clone github:eirikb/weecloud ~/src/weecloud
git clone github:fedoradesign/coloringbook-containers.git ~/src/coloringbook-containers
git clone github:holman/spark.git ~/src/spark
git clone github:joemiller/spark-ping.git ~/src/spark-ping
git clone github:Komish/config_files.git ~/src/jose_config_files
git clone github:Komish/hangman.git ~/src/jose_hangman
git clone github:mkaz/termgraph.git ~/src/termgraph
git clone github:mnagel/gnome-keyring-dumper.git ~/src/gnome-keyring-dumper
git clone github:mralexjuarez/mkdir-vagrant-structure
git clone github:nlhepler/pydot.git ~/src/pydot
git clone github:nojhan/liquidprompt.git ~/src/liquidprompt
git clone github:r043v/rdd.git ~/src/rdd
git clone github:rimraf/k.git ~/src/k
git clone github:sdelements/lets-chat.git ~/src/lets-chat
git clone github:ssllabs/ssllabs-scan.git ~/src/ssllabs-scan
git clone github:StafDehat/bashrc.git ~/src/brc
git clone github:StephenBrown2/archblocks.git ~/src/archblocks
git clone github:StephenBrown2/docpad-plugin-data.git ~/src/docpad-plugin-data
git clone github:StephenBrown2/findapkg.git ~/src/findapkg
git clone github:StephenBrown2/getmac.git ~/src/getmac
git clone github:StephenBrown2/holland_cloudbackup.git ~/src/holland_cloudbackup
git clone github:StephenBrown2/nato.py.git ~/src/nato
git clone github:StephenBrown2/sargraphjs.git ~/src/sargraphjs
git clone github:VirtusLab/ansible-modules-extras.git ~/src/ansible-modules-extras
git clone rackgit:alex-juarez/brownbag-slide-template.git ~/src/brownbag-slide-template
git clone rackgit:CORE/ctkapi-python.git ~/src/ctkapi-python
git clone rackgit:davi5522/rackerbot.git ~/src/rackerbot
git clone rackgit:EA-Team/eascripts.git ~/src/eascripts
git clone rackgit:ERMaintenances/linuxscripts.git ~/src/ER-Maint_linuxscripts
git clone rackgit:Linux-2nd-Austin/intensify.git ~/src/intensify
git clone rackgit:mart6141/Nucleus_Extensions.git ~/src/powershell
git clone rackgit:matt-martz/hammertime.git ~/src/hammertime
git clone rackgit:ricky-porter/pingo.git ~/src/pingo
git clone rackgit:shan5464/maintbuddy.git ~/src/maintbuddy
git clone rackgit:step7212/HybridControl-CloudServerScripts.git ~/src/HybridControl-CloudServerScripts
git clone rackgit:step7212/RESLinuxBot.git ~/src/RESLinuxBot
git clone rackgit:step7212/storagedot.git ~/src/storagedot
git clone rackgit:SupportTools/hammercloud.git ~/src/hammercloud
git clone rackgit:SupportTools/overtime.git ~/src/overtime
git clone rackgit:SupportTools/pyAppStats.git ~/src/pyAppStats
git clone rackgit:SupportTools/rdpwin.git ~/src/rdpwin
git clone rackgit:gist/b1ac7532f28fe627dace.git ~/src/proton_dark_css
git clone rackgit:davi5522/skills_matrix.git ~/src/skills_matrix